# Generated by Django 4.1.1 on 2023-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_alter_reserva_cantidad_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
